packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@hairy/utils': ^1.47.0
  '@vitejs/plugin-react': ^5.1.1
  destr: ^2.0.5
  react: ^19.2.4
  react-dom: ^19.2.4
  structure-id: ^1.2.9
  valtio: ^2.3.0

catalogMode: prefer

catalogs:
  cli:
    '@antfu/eslint-config': ^7.6.1
    '@antfu/ni': ^28.2.0
    babel-plugin-react-compiler: ^1.0.0
    bumpp: ^10.4.1
    eslint: ^10.0.2
    globals: ^17.4.0
    lint-staged: ^16.3.1
    simple-git-hooks: ^2.13.1
    tsdown: ^0.20.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    '@vitest/browser-playwright': ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    playwright: ^1.58.2
    tinyexec: ^1.0.2
    vitest: ^4.0.18
    vitest-browser-react: ^2.0.5
    vitest-package-exports: ^1.2.0
    yaml: ^2.8.2
  types:
    '@types/node': ^25.3.3
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true

trustPolicy: no-downgrade
