packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalog:
  '@hairy/utils': ^1.39.0
  '@vitejs/plugin-react': ^5.1.1
  react: ^19.2.0
  react-dom: ^19.2.0
  structure-id: ^1.2.9
  valtio: ^2.2.0
catalogs:
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    babel-plugin-react-compiler: ^1.0.0
    bumpp: ^10.3.1
    eslint: ^9.39.1
    globals: ^16.5.0
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    tsdown: ^0.16.0
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.2.1
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.7
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.10.0
    '@types/react': ^19.2.6
    '@types/react-dom': ^19.2.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
